# Generated by Django 5.1.6 on 2025-03-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_usersecurity_antiphishing_code_usersecurity_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(blank=True, related_name="user", to="auth.group"),
        ),
    ]
