# Generated by Django 5.1.6 on 2025-03-10 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_playerprofile_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
