# Generated by Django 5.1.6 on 2025-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0003_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prefered_games',
            field=models.ManyToManyField(blank=True, related_name='players', to='games.game'),
        ),
    ]
