# Generated by Django 5.1.6 on 2025-03-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_prefered_games_playerprofile_favorite_games_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerprofile",
            name="blocked_users",
            field=models.ManyToManyField(blank=True, to="users.playerprofile"),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="users.playerprofile"),
        ),
    ]
