# Generated by Django 5.1.6 on 2025-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="description",
        ),
        migrations.AddField(
            model_name="menu",
            name="is_protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menu",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
