# Generated by Django 5.1.6 on 2025-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="url",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
