# Generated by Django 5.1.6 on 2025-03-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_key",
                to="auth_core.apikeyclient",
            ),
        ),
    ]
