# Generated by Django 5.1.6 on 2025-03-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0002_alter_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='a_s',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='asn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
