# Generated by Django 5.1.6 on 2025-03-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0003_apikey_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_key",
                to="auth_core.apikeyclient",
            ),
        ),
    ]
