# Generated by Django 5.1.6 on 2025-03-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0005_objectpermission"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectpermission",
            old_name="object_id",
            new_name="owner_object_id",
        ),
        migrations.RemoveField(
            model_name="objectpermission",
            name="content_type",
        ),
        migrations.AddField(
            model_name="objectpermission",
            name="owner_content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_object",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectpermission",
            name="target_content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_object",
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectpermission",
            name="target_object_id",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
    ]
