# Generated by Django 5.1.6 on 2025-03-09 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0006_rename_object_id_objectpermission_owner_object_id_and_more"),
        ("geo", "0007_rename_administrativeprimary_administrativelevelprimary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("time_zone", models.CharField(max_length=255)),
                ("asn", models.CharField(max_length=255)),
                ("a_s", models.CharField(max_length=255)),
                ("is_proxy", models.BooleanField(default=False)),
                ("is_vpn", models.BooleanField(default=False)),
                (
                    "administrative_level_primary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.administrativelevelprimary"
                    ),
                ),
                (
                    "administrative_level_secondary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.administrativelevelsecondary"
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth_core.apikey"),
                ),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.city")),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.country")),
            ],
        ),
    ]
