# Generated by Django 5.1.6 on 2025-03-09 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0007_session"),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="token",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.KNOX_TOKEN_MODEL
            ),
            preserve_default=False,
        ),
    ]
