# Generated by Django 5.1.6 on 2025-03-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_core", "0009_session_created_at_session_updated_at"),
        ("geo", "0007_rename_administrativeprimary_administrativelevelprimary_and_more"),
        migrations.swappable_dependency(settings.KNOX_TOKEN_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="administrative_level_primary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.administrativelevelprimary",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="administrative_level_secondary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.administrativelevelsecondary",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="api_key",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="auth_core.apikey"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="geo.city"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="geo.country"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.KNOX_TOKEN_MODEL,
            ),
        ),
    ]
