# Generated by Django 5.1.6 on 2025-03-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("minor_unit", models.IntegerField(default=2)),
                ("symbol", models.CharField(max_length=10)),
                ("can_deposit", models.BooleanField(default=False)),
                ("can_withdraw", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "currencies",
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "exchanges",
            },
        ),
        migrations.CreateModel(
            name="FinancialApiProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coins_count", models.IntegerField(default=0)),
                ("active_markets_count", models.IntegerField(default=0)),
                ("market_cap", models.FloatField(default=0)),
                ("volume", models.FloatField(default=0)),
                ("btc_dominance", models.FloatField(default=0)),
                ("eth_dominance", models.FloatField(default=0)),
                ("market_cap_delta", models.FloatField(default=0)),
                ("volume_delta", models.FloatField(default=0)),
                ("avg_delta_percent", models.FloatField(default=0)),
                ("market_cap_ath", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Financial API Provider",
                "verbose_name_plural": "Financial API Providers",
            },
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("balance", models.FloatField()),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="financial.currency"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
                ("price_usd", models.FloatField()),
                ("percent_change_24h", models.FloatField()),
                ("percent_change_1h", models.FloatField()),
                ("percent_change_7d", models.FloatField()),
                ("price_btc", models.FloatField()),
                ("market_cap_usd", models.FloatField()),
                ("volume24", models.FloatField()),
                ("volume24a", models.FloatField()),
                ("csupply", models.FloatField()),
                ("tsupply", models.FloatField()),
                ("msupply", models.FloatField()),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="financial.currency"),
                ),
                (
                    "exchange",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="financial.exchange"),
                ),
                (
                    "financial_api_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="financial.financialapiprovider"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("balance", models.FloatField()),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="financial.currency"),
                ),
            ],
        ),
    ]
