# Generated by Django 5.1.6 on 2025-03-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currencies',
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial.currency'),
            preserve_default=False,
        ),
    ]
