# Generated by Django 5.1.6 on 2025-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_exchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialApiProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financial API Provider",
                "verbose_name_plural": "Financial API Providers",
            },
        ),
    ]
