# Generated by Django 5.1.6 on 2025-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0003_alter_ticker_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="csupply",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="msupply",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="tsupply",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
