# Generated by Django 5.1.6 on 2025-03-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0004_financialapiprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialapiprovider",
            name="active_markets_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="avg_delta_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="btc_dominance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="coins_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="eth_dominance",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="market_cap",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="market_cap_ath",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="market_cap_delta",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="volume",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="volume_24h",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="financialapiprovider",
            name="volume_delta",
            field=models.FloatField(default=0),
        ),
    ]
