# Generated by Django 5.1.6 on 2025-03-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0005_financialapiprovider_active_markets_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialapiprovider",
            name="volume_24h",
        ),
    ]
