# Generated by Django 5.1.6 on 2025-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
