version: "3.8"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: webcasino_sv
    ports:
      - "8000:8000"
    # volumes:
    #   - ../:/app
    environment:
      - PYTHONUNBUFFERED=1
      # - DATABASE_URL=postgres://dwebcasino:dwebcasino@db:5433/dwebcasino
