services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dwebcasino
      POSTGRES_PASSWORD: dwebcasino
      POSTGRES_DB: dwebcasino
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: