services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    environment:
      - DATABASE_URL=postgres://user:password@db:6379/valkeydb
      - VALKEY_SECRET_KEY=your_secret_key

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-commander
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - valkey_network

volumes:
  valkey-db-data:

networks:
  valkey_network:
    driver: bridge