# Generated by Django 5.1.6 on 2025-02-28 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='decks',
            field=models.ManyToManyField(related_name='tables', to='card_games.deck'),
        ),
    ]
