# Generated by Django 5.1.6 on 2025-02-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_games', '0003_texasholdem_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texasholdem',
            name='ante',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='big_blind',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='flop_cards',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_all_in',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_bet',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_call',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_check',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_fold',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_players',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_raise',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_rounds',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='max_showdown',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='min_players',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='river_cards',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='small_blind',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='turn_cards',
        ),
    ]
