# Generated by Django 5.1.6 on 2025-03-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_games', '0004_remove_texasholdem_ante_remove_texasholdem_big_blind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name_plural': 'decks'},
        ),
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
    ]
