# Generated by Django 5.1.6 on 2025-03-02 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_games', '0005_alter_deck_options_remove_deck_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texasholdem',
            options={},
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='decks',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decks', models.ManyToManyField(related_name='tables', to='card_games.deck')),
            ],
            options={
                'verbose_name_plural': 'tables',
            },
        ),
        migrations.AddField(
            model_name='texasholdem',
            name='table_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_games.table'),
            preserve_default=False,
        ),
    ]
