# Generated by Django 5.1.6 on 2025-03-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_games', '0006_alter_texasholdem_options_and_more'),
        ('games', '0003_alter_game_options_game_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.game')),
                ('deck_cards', models.IntegerField()),
                ('timeout', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('games.game',),
        ),
        migrations.AlterModelOptions(
            name='texasholdem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='deck_cards',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='table_ptr',
        ),
        migrations.RemoveField(
            model_name='texasholdem',
            name='timeout',
        ),
        migrations.AddField(
            model_name='texasholdem',
            name='poker_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_games.poker'),
            preserve_default=False,
        ),
    ]
