# Generated by Django 5.1.6 on 2025-03-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_games', '0007_poker_alter_texasholdem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poker',
            name='deck_cards',
        ),
        migrations.AddField(
            model_name='texasholdem',
            name='deck_cards',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
