# Generated by Django 5.1.6 on 2025-03-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdministrativeLevelPrimary",
            fields=[
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AdministrativeLevelSecondary",
            fields=[
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "primary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.administrativelevelprimary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "primary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="geo.administrativelevelprimary",
                    ),
                ),
                (
                    "secondary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="geo.administrativelevelsecondary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("code_long", models.CharField(max_length=3)),
                ("code_numeric", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=255)),
                ("name_official", models.CharField(max_length=255)),
                (
                    "continent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.continent"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="administrativelevelprimary",
            name="country",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.country"),
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.city")),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("complement", models.CharField(max_length=255)),
                ("floor", models.CharField(max_length=10)),
                ("door", models.CharField(max_length=10)),
                ("street", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.street")),
            ],
        ),
    ]
