# Generated by Django 5.1.6 on 2025-03-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("code_long", models.CharField(max_length=3)),
                ("code_numeric", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=255)),
                ("name_official", models.CharField(max_length=255)),
                ("slug_name", models.SlugField(max_length=255)),
                ("slug_name_official", models.SlugField(max_length=255)),
                (
                    "continent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.continent"),
                ),
            ],
        ),
    ]
