# Generated by Django 5.1.6 on 2025-03-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="slug_name",
        ),
        migrations.RemoveField(
            model_name="country",
            name="slug_name_official",
        ),
    ]
