# Generated by Django 5.1.6 on 2025-03-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeLevelPrimary",
            fields=[
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.country")),
            ],
        ),
        migrations.CreateModel(
            name="AdministrativeLevelSecondary",
            fields=[
                ("code", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "primary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.administrativelevelprimary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                (
                    "primary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.administrativelevelprimary"
                    ),
                ),
                (
                    "secondary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="geo.administrativelevelsecondary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.city")),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("floor", models.CharField(max_length=10)),
                ("door", models.CharField(max_length=10)),
                ("street", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geo.street")),
            ],
        ),
    ]
