# Generated by Django 5.1.6 on 2025-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_administrativelevelprimary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="complement",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
