# Generated by Django 5.1.6 on 2025-03-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_address_complement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="primary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.administrativelevelprimary",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="secondary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.administrativelevelsecondary",
            ),
        ),
    ]
