# Generated by Django 5.1.6 on 2025-03-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_alter_city_primary_alter_city_secondary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="primary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.administrativelevelprimary",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="secondary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.administrativelevelsecondary",
            ),
        ),
    ]
