# Generated by Django 5.1.6 on 2025-03-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0005_alter_city_primary_alter_city_secondary"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdministrativeLevelPrimary",
            new_name="AdministrativePrimary",
        ),
        migrations.RenameModel(
            old_name="AdministrativeLevelSecondary",
            new_name="AdministrativeSecondary",
        ),
    ]
