# Generated by Django 5.1.6 on 2025-03-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0006_rename_administrativelevelprimary_administrativeprimary_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdministrativePrimary",
            new_name="AdministrativeLevelPrimary",
        ),
        migrations.RenameModel(
            old_name="AdministrativeSecondary",
            new_name="AdministrativeLevelSecondary",
        ),
    ]
