# Generated by Django 5.1.6 on 2025-03-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('games', '0002_game_created_at_game_updated_at_alter_game_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='game',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
