name: API Tests

on:
  push:
    branches:
      - main
      - preprod
      - prod
      
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17 
        env:
          POSTGRES_USER: webcasino
          POSTGRES_PASSWORD: webcasino
          POSTGRES_DB: webcasino
          
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-timeout=5s --health-start-period=10s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      
      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -U webcasino -d webcasino; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://webcasino:webcasino@localhost:5432/test_db" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "IP_INFO_URL=${{ env.IP_INFO_URL }}" >> $GITHUB_ENV
          echo "IP_INFO_TOKEN=${{ secrets.IP_INFO_TOKEN }}" >> $GITHUB_ENV
      - name: Run tests
        run: pytest
